### ISSUE TITLE
plugins/slate: undo/redo is broken with slate

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#127]
upstream: https://github.com/ianstormtaylor/slate/issues/271

**Comment by arekkas** [comment]
Here's a fiddle that get's it working: https://jsfiddle.net/uvg4cdfa/1/

**Comment by arekkas** [comment]
This issue is tightly coupled to #252. ping @inyono for brain power.

The core issue is that `editorState.isNative` is a flag which is set when writing text with the keyboard in slate. It skips the slate react rendering and uses the contenteditable rendering instead. This allows for better performance. Because it skips rendering, we need to set isNative to false when undoing/redoing stuff, otherwise there will be exceptions as well as weird rendering behaviour.

So, right now undo and redo works by having a key handler on the root editor dom node that listens on `strg+z`. This will dispatch an action `UNDO` that will be handled by redux-undo:

```jsx
export const rawEditableReducer = (state: Object, action: { type: string }) => {
  // this reducer will not be executed when an UNDO action is triggered, because 
  // undoable wants to reduce side effects, i guess?
  switch (action.type) {
    default:
      return {
        ...state,
        cells: decorate(cells(state.cells, action)),
        cellOrder: cellOrder(state.cells || [])
      }
  }
}

export const editable = (id: string) => {
  return undoable(rawEditableReducer)
}
```

Because of that, it is impossible to hook in a custom plugin reducer that would have been able to do something like this

```jsx
const slateReducer = (state, action) => {
    if (action.type === 'UNDO) {
      return ({
        ...state,
        content: {
          ...state.content,
          state: {
            ...state.content.state,
            editorState: state.content.state.editorState.merge({ isNative: false })
          }
        }
      })
    }
}
```

which could have been a clean solution from the API point of view.

The other possibility is to introduce a new hook `handleUndoAction` that looks something like

```jsx
export const handleUndoAction = (e: KeyboardEvent, { content: { state: { editorState } } }: Props) => new Promise((resolve: (state: any) => void) => {
  // onChange({ editorState: editorState.merge({ isNative: false }) })
  resolve()
})
```

which looks like a clean solution, but there are actually a several sever problems here:

1. We don't know which cell changed because redux-undo simply swaps the whole tree and we redux-undo does not tell me which action it was that caused the original state change.
2. because of that we would either need to bulk update all cells with a slate plugin and isNative: flase, or
3. use something like `componentWillReceiveProps`. In this case however, we would need to identify that the current state change was caused by a redo/undo action, which is again not trivial
4. Another issue is that `onChange` is not defined, we would need to pass it down, i think the best idea would be to have a something like this: `handleUndoAction = (e: Event, c: Component) => c.props.onChange()`
5. While it is nice that we have an onChange here, we add another layer of complexity because this onChange trigger should not push another state into redux-undo
6. We could also return the state directly, which is not ideal because it would disallow asnyc code
7. We could return the state in with `resolve(state)` which would allow async code, but it would mean that we have to track the state from the strg+z event callback handler back to the react component which is basically impossible

This is a fucking nightmare. Please, if you have any ideas @inyono let me know.

**Comment by inyono** [comment]
> Because of that, it is impossible to hook in a custom plugin reducer that would have been able to do something like this

Now I understand what you meant in the other issue ^^. So the main issue is that we don't know what is modified by undo/redo (and we need to know so that we can deactivate `isNative` beforehand)?

> While it is nice that we have an onChange here, we add another layer of complexity because this onChange trigger should not push another state into redux-undo

Doesn't it makes sense to pass something like `undoable` or `commit` to `onChange` anyway? With this, plugins could debounce undo steps and mark some state changes as not undoable (e.g., because it is an internal one).

**Comment by arekkas** [comment]
> So the main issue is that we don't know what is modified by undo/redo (and we need to know so that we can deactivate isNative beforehand)?

Yes, sort of. It's actually not a problem to apply isNative=false in every slate instance, it doesn't really do anything. But if you have multiple plugins that handle onUndo you could get in trouble.

> Doesn't it makes sense to pass something like undoable or commit to onChange anyway? With this, plugins could debounce undo steps and mark some state changes as not undoable (e.g., because it is an internal one).

Yes, debouncing is actually quite important for e.g. the spacer plugin. This makes sense, I will look into it.

**Comment by arekkas** [comment]
Superseeded by #257
