### ISSUE TITLE
plugins/slate: link is broken

### ISSUE THREAD

**Issue by inyono** [ory-am/editor#159]
- [x] upstream: https://github.com/ianstormtaylor/slate/issues/255
- [ ] upstream: https://github.com/ianstormtaylor/slate/issues/349
- [x] upstream:  https://github.com/ianstormtaylor/slate/issues/363
- [x] upstream: https://github.com/ianstormtaylor/slate/issues/347
- [x] upstream: https://github.com/ianstormtaylor/slate/issues/432

**Comment by arekkas** [comment]
I think the #349 is more of a UX issue, it's not something we have to address in this issue

**Comment by inyono** [comment]
note /self: upstream closed
