### ISSUE TITLE
core: decide if modes should be merged

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#183]
Currently, there are several modes like `Write`, `Rearrange`, ...

We need to think about grouping things or even have all modes at once, except preview.

**Comment by arekkas** [comment]
Repeated feedback showed that it's ok as it is now, but needs to be addressed when more things are added

**Comment by bkniffler** [comment]
Why is a separation between rearrange, resize and add needed? Wouldn't edit, layout and preview make sense?

**Comment by arekkas** [comment]
I think that this makes sense from a user perspective. One issue however is that we're currently using div overlays to catch resize events even when flash or other rich content is used in a cell. It would require quite some refactoring (if it's even sanely possible) to make both modes work with this limitation.

So for now this is buried deep in the back log :)
