### ISSUE TITLE
plugins/slate: editorState.isExpanded fails sometimes

### ISSUE THREAD

**Issue by inyono** [ory-am/editor#192]
Steps to reproduce:
- Go in edit mode
- Double-Click a word to select it

If the double-click is done too fast, then slate triggers only one state change (probably for the cursor change) instead of two (cursor change and selection expansion). Occurs only if the slate component wasn't focused beforehand.

**Comment by arekkas** [comment]
I think this should be resolved with the 0.4.0 release.

**Comment by arekkas** [comment]
no, unfortunately it is not resolved.

**Comment by arekkas** [comment]
still happening in slate 0.15
