### ISSUE TITLE
CSS Frameworks

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#20]
Bootstrap is outdated (can't find the blogpost on why twitter needs to adapt to current design trends). Therefore, alternatives must be found.

For now, there are two candidates. Feel free to extend:

- https://github.com/zurb/foundation
- https://github.com/yahoo/pure/

**Comment by inyono** [comment]
in no particular order:
* http://skel.io used for the templates on http://html5up.net
* http://material-ui.com and other implementations
* http://susy.oddbird.net/ and similar tools

**Comment by arekkas** [comment]
do you have any experience with one of those? For now, pure seems like a good fit although I have zero experience with any of those.

**Comment by inyono** [comment]
Nope, I'm only brainstorming ;)

**Comment by arekkas** [comment]
Pure is really..not beautiful

**Comment by inyono** [comment]
So may/should I take some time to research and let my guts choose another one?

**Comment by arekkas** [comment]
Foundation looks kinda solid but it looks sometimes a little off (especiall the positioning of text in buttons and labels).

Also there's bootstrap 4 on the horizon: http://v4-alpha.getbootstrap.com/

Although it doesn't look like they changed much in the design.

**Comment by inyono** [comment]
I used Foundation for a small project, and it was relatively easy to customize the appearance. There will also be a new major release, soon.

I also find the Sass-only approach (e.g. with Susy) pretty interesting, although I have to experience with that. I like the "Do One Thing and Do It Well" kinda philosophy behind it instead of using a complete CSS framework that offers everything but where you only need a small percentage.

**Comment by arekkas** [comment]
Yup from what I've read on the internetz Foundation is the choice to go for designers as it's much easier to customize (customizing bootstrap sucks bigtime imho)

**Comment by arekkas** [comment]
Do you have any frameworks similar to Susy for e.g. Forms or Buttons? I like the idea of having a highly customizable grid system, especially if we're talking about the editor and maybe some customizable content-grid system

**Comment by inyono** [comment]
Nothing springs to mind, but there are basically small libraries/mixins for *everything*, see e.g. http://www.sache.in/ ... I think we should be able to find libraries that match our needs.

**Comment by arekkas** [comment]
[Semantic UI](http://semantic-ui.com/introduction/getting-started.html) looks like something we could bootstrap some projects with as well

**Comment by inyono** [comment]
Yeah, looks interesting. Although I didn't really understand why it needs gulp and I'm kinda disappointed that it has no Sass support ;)
