### ISSUE TITLE
core: reduce bundle size

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#217]
ideas:

* [ ] remove material ui or wait until version 2 is out (hopefully more leightweight)
* [ ] check if postcss is really being used and if not remove it @inyono 
* [ ] introduce a lightweight renderer that has zero dependencies

**Comment by inyono** [comment]
> @inyono is webpack currently including all dependencies or only files that are required by the code?

Webpack should only include dependencies that are required by the code. Webpack 2 should even be better because of tree-shaking (have to review the config for this though, not sure if we do all the needed optimisations).

**Comment by arekkas** [comment]
ok cool, should I create an issue for it?

**Comment by inyono** [comment]
I don't care, we can also track this here :) Apparently, http://rollupjs.org/ is often used for libraries. Will have to look into this, though.

**Comment by arekkas** [comment]
ok let's keep it here then :)

**Comment by inyono** [comment]
Tree-Shaking should work with our current config

**Comment by arekkas** [comment]
So if it works, we don't need rollup.js, right?

**Comment by inyono** [comment]
Yeah, although that could improve the bundle size. Isn't straight forward to integrate, though.

We could also try if google closure helps (there is a webpack plugin for this)

**Comment by mkozhukharenko** [comment]
> We could use inline-styles for html elements that are only visible during layout/edit mode.

why not simple css ?

`slate` should not come with the core as well. Or it's essential, isn't it?

`react-tap-event-plugin` will be gone together with a `material-ui`

**Comment by arekkas** [comment]
Yes, without slate most of the experience will be missing. I think it is good to split things apart, but we should try to not make it too hard for developers to use it, this for example is too complex imho:

```
import Editor from 'ory-editor'
import EditorUI from 'ory-editor-ui'
import SlatePlugin from 'ory-editor-plugin-slate
// ...
```

One issue with material-ui is, that we use the svg icons in basically all of the plugins. Maybe, at some point, we need to extract the svgs we use and include only them. Then we could get truly rid of material-ui.

**Comment by arekkas** [comment]
Maybe it makes more sense to keep most of these things within the main npm module and rely on [webpack tree-shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html) to remove unneccessary exports from the build. Thus, a customized editor instance could look like this:

```
import Editor, { DisplayControls, PluginDrawer, plugins, actions } from 'ory-editor'

const slateConfig = { /* ... */ }

const editor = new Editor({
  plugins: {
    content: [
      plugins.content.image,
      plugins.content.slate(slateConfig),
      plugins.content.spacer,
      plugins.content.video
    ],
    layout: [ /* ... */ ]
  }
})

class App extends Component {
  onSomeAction = () => {
    editor.dispatch(actions.cell.removeCell('1234'))
  }

  render() {
    return (
      <div>
        <div style={{ margin: '0 200px' }}>
          <Editable editor={editor} state={state} onChange={(s) => console.log(s)}/>
        </div>
        <DisplayControls someSetting editor={editor}/> <!-- The buttons on the bottom left for toggling display modes -->
        <PluginDrawer someSetting editor={editor}/> <!-- The drawer that opens in insert mode and displays all the plugins -->
      </div>
    );
  }
}
```

**Comment by mkozhukharenko** [comment]
> rely on webpack tree-shaking to remove unneccessary exports from the build.

so, the real benefit (smaller size of the editor) will receive only users who uses webpack 2? 

you first example (below)
```
import Editor from 'ory-editor'
import EditorUI from 'ory-editor-ui'
import SlatePlugin from 'ory-editor-plugin-slate
// import ...

const editor = new Editor({ Plugins: ...., UI: EditorUI, ..., ... })
``` 
acually the same as second. The only difference is that the plugins located in different packages (rather than in the core). And it's harder to maintain (but it can be easier if have multiple npm packages in one repo. It's possible to to manage inter-package dependencies in one monorepo using [lerna](https://lernajs.io/_)

> we should try to not make it too hard for developers to use it, this for example is too complex imho 

don't think so.
such plugin-centric design uses, e.g. [draft-js-plugins](https://github.com/draft-js-plugins/draft-js-plugins) and [slate](https://github.com/ianstormtaylor/slate)

**Comment by arekkas** [comment]
> so, the real benefit (smaller size of the editor) will receive only users who uses webpack 2?

Yes, for now!

> acually the same as second. The only difference is that the plugins located in different packages (rather than in the core). And it's harder to maintain (but it can be easier if have multiple npm packages in one repo. It's possible to to manage inter-package dependencies in one monorepo using lerna

Yep, you're right here. I think the difference is that the slate plugin is actually a core plugin. Usually when you use the editor you want slate as well, otherwise you can't edit text. Thus, just to get started, you need to install both dependencies, which feels kinda weird, don't you think?

Thanks for the tip on lerna, haven't seen that project before!

**Comment by mkozhukharenko** [comment]
> Thus, just to get started, you need to install both dependencies, which feels kinda weird, don't you think?

you are right. This dependency - slate - is core one. I only thought about a case then somebody wants different editor (e.g. drafjs). But it can be skipped for now.
