### ISSUE TITLE
core: jest snapshots cause "injectEnvironment called twice"

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#238]
upstream https://github.com/facebook/react/issues/7386

Once we're on react 0.15.4 we can remove all `jest.mock('react-dom')` calls.

**Comment by inyono** [comment]
We are already on React 15

**Comment by arekkas** [comment]
sorry, 0.15.4 not 0.14

**Comment by gaearon** [comment]
This was fixed in React 15.4.0 which is [out today](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html).

**Comment by arekkas** [comment]
Thanks !

**Comment by arekkas** [comment]
Unfortunately, some dependencies still depend on the React internals (like react-inject-tap-event) which is why we can't upgrade to 15.4 at the moment, re-opening.
