### ISSUE TITLE
plugin/slate: how to add modals for e.g. links

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#263]
Right now, the slate plugins relies on `window.prompt` to retrieve the url / title of a link or the math formula of a katex element. First, I want the prompt to be pre-filled with the curren url/title and second I want to use something like material ui modal instead.

@inyono is it currently possible to get the state of the node that is currently focused in the button component of a slate plugin?

**Comment by arekkas** [comment]
Another issue with modals is that we lose focus, although we have an ancestor with `className="editor-container"`. Not sure why it's blurring.

**Comment by inyono** [comment]
> @inyono is it currently possible to get the state of the node that is currently focused in the button component of a slate plugin?

I don't think so. You might be able to get it by using some adaption of `isActive` in the button component.

**Comment by arekkas** [comment]
This is now resolved for links (not katex though)
