### ISSUE TITLE
plugin/slate: electing text by double-clicking doesn't work on linked text

### ISSUE THREAD

**Issue by Knorrke** [ory-am/editor#269]
When I double click on linked text in edit mode the cursor jumps to the end of the paragraph instead of selecting the clicked word. This only happens on links, it works fine with plain text as well as bold, italic, underlined and inline code.

**Comment by arekkas** [comment]
Thanks! Upstream: https://github.com/ianstormtaylor/slate/issues/440

**Comment by arekkas** [comment]
This is a firefox issue
