### ISSUE TITLE
plugin/slate: blocks after lists are div, not paragraph

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#273]
![lists-broken](https://cloud.githubusercontent.com/assets/3372410/20462097/1565bed0-af13-11e6-9c42-5f80033e473b.gif)

**Comment by arekkas** [comment]
@inyono I think this happens because the block is of type 'paragraph' not 'PARAGRAPH/PARAGRAPH' but I'm not sure where that is being set. For some reason it seems like slate plugins have names too (but they are different from the node type names)?

![a4wqtgaqw34et](https://cloud.githubusercontent.com/assets/3372410/20484553/f551213a-aff7-11e6-8f19-efe6dca78982.PNG)

**Comment by inyono** [comment]
Should be set as default_plugin in the Slate plugin itself and passed down to lists.

**Comment by inyono** [comment]
Not sure what's happening there, will have to look deeper. A quick fix would be to rename the paragraph node to paragraph. The name is currently hardcoded in the content.js files, though. We should probably instead use the exported constants from the plugins itself.

**Comment by inyono** [comment]
Update: `slate-edit-list` handles this case correctly, so we are doing something wrong.

**Comment by arekkas** [comment]
One issue was that `this.DEFAULT_NODE` was undefined when the plugin was called because it was defined as a static member. I don't quite remember if I uploaded those changes or not, maybe check it yourself.

**Comment by inyono** [comment]
Yeah, you uploaded those changes.

**Comment by inyono** [comment]
You're right, this was also an issue in the plugin itself (really need to refactor those plugins to use functions instead ^^). It works now for new lists. I suppose that our markup in our initial state is wrong (since `slate-edit-list` makes some assumptions).
