### ISSUE TITLE
Any plans for musical notation via Lilypond?

### ISSUE THREAD

**Issue by JonasBley** [ory-am/editor#28]
Are there any plans to integrate Lilypond into the editor? 

Would be extremely cool for any music based project :)

**Comment by arekkas** [comment]
Not right now, but it might be a plugin in the future :)

**Comment by JonasBley** [comment]
Allright, thanks for the fast answer :)

**Comment by inyono** [comment]
Since this doesn't concern the editor itself in this state, I'll close this issue for now. But like @arekkas said, there might be a plugin in the future, especially if it is relevant for Serlo ;)
