### ISSUE TITLE
File Structure 

### ISSUE THREAD

**Issue by fredhampton** [ory-am/editor#282]
Where are the files that constitute the pages that are edited within the Ory editor ?

Thanks

**Comment by arekkas** [comment]
Hey, all examples are here: https://github.com/ory-am/editor/tree/master/examples

The home page is this: https://github.com/ory-am/editor/tree/master/examples/home/src

**Comment by fredhampton** [comment]
Thanks !!



On November 21, 2016 at 2:45:48 PM, Aeneas (notifications@github.com) wrote:

Hey, all examples are here: https://github.com/ory-am/editor/tree/master/examples

The home page is this: https://github.com/ory-am/editor/tree/master/examples/home/src

**Comment by arekkas** [comment]
welcome!
