### ISSUE TITLE
plugin/slate: new line after inline math-formula duplicates formula

### ISSUE THREAD

**Issue by Knorrke** [ory-am/editor#285]
Creating a new line after inline katex formula duplicates the formula.

![serlo](https://cloud.githubusercontent.com/assets/11499926/20666970/362c1e8e-b567-11e6-8a91-aceb44df65af.gif)

**Comment by arekkas** [comment]
This has probably to do something with split block transformation

**Comment by inyono** [comment]
upstream: https://github.com/ianstormtaylor/slate/issues/472
