### ISSUE TITLE
general: check out antd

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#286]
https://ant.design/components/carousel/

**Comment by bkniffler** [comment]
I've just discovered ory-am, really cool project. I've also been using antd, it seems like the most feature-complete UI library for react. But why would the ory editor need that?

**Comment by arekkas** [comment]
Hey thanks for the positive feedback! The editor is in a very early stage, but it is possible to get it working already. If you need any help, let me know either here or on gitter :) There are still some rough edges in the API and if you plan on installing the editor via npm let me know, so I can prioritize a few fixes.

Regarding your question: my idea was to have a plugin pack with stuff like buttons, forms, carousels, ... - all of which antd is providing. So I thought it might be a good idea to give it a look when implementing the plugins.

By the way, we are working on some tempaltes for creating and publishing your own plugins via npm. :)

**Comment by mkozhukharenko** [comment]
@arekkas didn't you think about replacing a `material-ui` dependency with the `ant`?

**Comment by arekkas** [comment]
Yes, that as well, although I like material-ui more from a design perspective. Still, it's quite heavy. Optimally it will be replaced with something self-made that has no additional dependencies

**Comment by mkozhukharenko** [comment]
>  Still, it's quite heavy. Optimally it will be replaced with something self-made 

it's a good point, since editor requires only simple components like icons, buttons, menu/list items (sidebar & toolbars)

there are css framework which can apply material design on top of any element - http://materializecss.com
- [buttons](http://materializecss.com/buttons.html )
- [icons](http://materializecss.com/icons.html)

**Comment by arekkas** [comment]
Cool, I haven't seen that project before. I definitely have to take a closer look!

**Comment by mkozhukharenko** [comment]
and simple class-based styling is easier to customize for other user. E.g. we are interested in using Ory-am editor but want to apply custom styles. 

>  Regular CSS is easier to for consumers override and theme—this is especially important when authoring a library instead of an application. We have some use cases where we want to allow consumers to do this after build time, which is nearly impossible to do with inline styles that are applied in an application's JS bundle. [(source)](https://github.com/palantir/blueprint/wiki/Frequently-Asked-Questions#4-what-about-inline-stylesthose-are-all-the-rage-these-days-right)

**Comment by arekkas** [comment]
Yes, I agree 100%. We will also expose APIs for things like *insert a cell below that one* or *update this cell's content*, so you are able to completely create your own UI, and we simply ship a few generic components that are customizable to some point. What do you think of this?

**Comment by mkozhukharenko** [comment]
> you are able to completely create your own UI

agree. This should be one of the principal ideas of the Editor

>  and we simply ship a few generic components that are customizable to some point

and these generic components (like video, image, reach-text) should be pluggable. They should not come with the editor itself, but a user can plug them if needed.

**Comment by arekkas** [comment]
> agree. This should be one of the principal ideas of the Editor

Most of this is already possible, we just have to document it and expose the APIs through th enpm package.

> and these generic components (like video, image, reach-text) should be pluggable. They should not come with the editor itself, but a user can plug them if needed.

Yes, I think that makes sense if the components have additional dependencies which are not part of the main editor!

**Comment by arekkas** [comment]
superseded by #318

**Comment by rocky-peng** [comment]
```
import React, { Fragment, PureComponent } from 'react';
// The editor core
import Editor, { Editable, createEmptyState } from 'ory-editor-core';
import 'ory-editor-core/lib/index.css'; // we also want to load the stylesheets

// Require our ui components (optional). You can implement and use your own ui too!
import { Trash, DisplayModeToggle, Toolbar } from 'ory-editor-ui';
import 'ory-editor-ui/lib/index.css';

// Load some exemplary plugins:
import slate from 'ory-editor-plugins-slate'; // The rich text area plugin
import 'ory-editor-plugins-slate/lib/index.css'; // Stylesheets for the rich text area plugin
import parallax from 'ory-editor-plugins-parallax-background'; // A plugin for parallax background images
import 'ory-editor-plugins-parallax-background/lib/index.css'; // Stylesheets for parallax background images
require('react-tap-event-plugin')(); // react-tap-event-plugin is required by material-ui which is used by ory-editor-ui so we need to call it here

const plugins = {
  content: [slate()], // Define plugins for content cells. To import multiple plugins, use [slate(), image, spacer, divider]
  layout: [parallax({ defaultPlugin: slate() })], // Define plugins for layout cells
};

// Creates an empty editable
const content = createEmptyState();

// Instantiate the editor
const editor = new Editor({
  plugins,
  // pass the content state - you can add multiple editables here
  editables: [content],
});

export default class Monitor extends PureComponent {
  render() {
    return (
      <div>
        <div className="App-header">
          <h2>Welcome to React</h2>
        </div>

        {/* Content area */}
        <Editable editor={editor} id={content.id} />

        {/*  Default user interface  */}
        <Trash editor={editor} />
        <DisplayModeToggle editor={editor} />
        <Toolbar editor={editor} />
      </div>
    );
  }
}

```

the complete demo code :  git@github.com:rocky-peng/ant-design-pro.git  
```
npm install
npm start 

access the page :  http://localhost:port/#/dashboard/fulltext1  
then the issue will be occured.  thanks for your help
```

**Comment by davidfurlong** [comment]
I use antd design successfully - the button issue is a different issue
