### ISSUE TITLE
vendor: review peerDependencies

### ISSUE THREAD

**Issue by inyono** [ory-am/editor#290]
Most of these shouldn't be peerDependencies:
```
warning Unmet peer dependency "react-dnd@^2.0.0".
warning Unmet peer dependency "katex@^0.6.0".
warning Unmet peer dependency "react-tap-event-plugin@^1.0.0 || ^2.0.0".
warning Unmet peer dependency "slate@^0.14.6".
warning Unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning Unmet peer dependency "slate@^0.14.6".
warning Unmet peer dependency "react-tap-event-plugin@^2.0.0"
```

**Comment by arekkas** [comment]
could you elaborate? :)

**Comment by inyono** [comment]
E.g. Redux is not necessarily needed by third-party apps using our Editor. So this shouldn't be an peerDependency, just because we use it internally. React on the other hand should be an peerDependency, because you can't use the Editor without it and we don't want to include React's package twice.

**Comment by arekkas** [comment]
:+1:

**Comment by arekkas** [comment]
I think this is resolved now? The peerDependencies are currently:

```
  "peerDependencies": {
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-tap-event-plugin": "^2.0.0"
  },
```

react-tap-event-plugin has to be a peer dependency because it monkey patches react

**Comment by inyono** [comment]
Yeah, looks much better. Since peerDependencies aren't enforced anymore, I don't have a problem with the hard constraints of react-*

**Comment by arekkas** [comment]
perfect 👌
