### ISSUE TITLE
build: how to deal with css?

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#296]
At the moment, developers must include the ory css file in their javascript:

```
import Editor, { Editable, Controls, PluginService, plugins, createEmptyState } from 'ory-editor'
import 'ory-editor/dist/styles.css'
```

Can we circumvent this? How would this look in a bower module / plain javascript?

ping @inyono

**Comment by inyono** [comment]
Nope, they don't. `<link rel="stylesheet" href="node_modules/ory-editor/dist/styles.css" />` works too. As long as `styles.css` is part of the bundle (i.e. bower bundle / dist zip file / whatever), there shouldn't be a problem.

**Comment by arekkas** [comment]
Ok, but the developer has to explicitly include the css file, right? There is no way for us to do that automatically

**Comment by inyono** [comment]
Yep

**Comment by inyono** [comment]
Yep. Except when we use inline styles.

**Comment by inyono** [comment]
After some more thought, I find the idea of inline styles quite appealing. No need for bundling from our side and users of the editors don't have to include anything. Styles that are only used in the editor need no CSS file anyway, do they (increased bundle size isn't such a big issue since the users of the websites don't get them)? We would need to find a way how to handle CSS for the rendered plugins, though.

**Comment by arekkas** [comment]
Exactly! The styles used by the editor are usually some magic to make drag and drop work and similar. However, we can't have css selectors in inline styles, right? So how would we deal with `:hover, :after, :active, ...`?

**Comment by inyono** [comment]
Yeah, you're right, pseudo-classes are problematic. We could use something like [aphrodite](https://github.com/Khan/aphrodite) that creates a `style` tag, though. See [css-in-js](https://github.com/MicheleBertoli/css-in-js) for possible alternatives.

**Comment by arekkas** [comment]
So how would we deal with the responsive grid that we're currently including? This is probably too massive for a style tag?

**Comment by arekkas** [comment]
One idea would be to:

* allow setting the css classname generation schema for rows and cells
* provide a default css with our grid
* encourage people to use their own grid (it needs to be row/cell based)

However, we would need to either get rid of the special flexbox grid for layout / insert mode, or somehow disable the default grid and replace it with flexbox for those cases.

In general, I think it would be good to get rid of the css-grid hard dependency.
