### ISSUE TITLE
build: "node" engine

### ISSUE THREAD

**Issue by inyono** [ory-am/editor#299]
```
error ory-editor@0.0.15: The engine "node" is incompatible with this module. Expected version "~6.6.0".
```
Current node LTS is 6.9.2. And why do we even need to specify the engine? Why can't I use v7 for example? @arekkas 

Walkaround: `yarn install --ignore-engines`

**Comment by arekkas** [comment]
Sorry, there was an issue with the built and I thought it might be caused by the node version, but it really was a problem with yarn cache. However, we should only put versions in there that are known to be working, for example `~6.0.0`

**Comment by inyono** [comment]
> However, we should only put versions in there that are known to be working, for example ~6.0.0

I see the point for older node versions. But IMHO, it shouldn't be so restrictive about newer versions. E.g. v7 should work fine, too (maybe even v4/v5). Not everyone is using LTS versions of node and if you don't know what's going on, even `npm install` fails.
