### ISSUE TITLE
plugins/slate: selecting text, open link dialogue, typing causes dialogue loss

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#302]
![bugg](https://cloud.githubusercontent.com/assets/3372410/21384200/d4352756-c769-11e6-9234-19221898a7f4.gif)

**Comment by mkozhukharenko** [comment]
the solution is to manually set a focus on input in the dialog.

**Comment by arekkas** [comment]
yup, perfect!

**Comment by elbotho** [comment]
Related and might not be worth an own issue:
Users should be able to close dialogs with [ESC].
