### ISSUE TITLE
build: remove react-css-modules dependency

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#305]
The original idea behind react-css-modules was to have automated namespacing. However, I assumed that it would be possible to override styles of the editor. This does not seem to be the case as the css classes are named randomly on each build, thus making it impossible to modify the styles.

My proposal is to remove `react-css-modules` from everywhere and instead prefix all classes with `ory-`, or alternatively `ory-editor-` or `editor-` or `oe-`. We still have to figure out how to avoid name collisions (e.g. two react components sharing the same css classes).

I would love to get your input on this @inyono

**Comment by arekkas** [comment]
To avoid name collisions I suggest to use the path as prefix. For example, `Components/Cell/Empty` would result in prefix `ory-cell-empty-`.

**Comment by inyono** [comment]
Sounds good to me, should reduce some of the complexity we also have when outsourcing plugins.

**Comment by arekkas** [comment]
done!
