### ISSUE TITLE
controls: move ui elements to a new repository

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#309]
The idea is to move ui elements such as the toolbar on the right and the drawer on the left to a new repository: `ory-editor-ui`. For the plugins we only need the svg icons which we can easily extract from material-ui, probably reducing the size of the core component drastically and also getting rid of react-tap-event.

**Comment by inyono** [comment]
Currently, we don't import the whole `material-ui` anyway, do we? So this shouldn't really reduce the font size (at least not more than moving the plugins in its own repository)

**Comment by arekkas** [comment]
The idea is that the toolbars we provide are probably not what people are looking for. So by moving the ui elements to a separate repo we allow them to use only the "core", which will also be less bloated
