### ISSUE TITLE
all: make this a mono-repo with multiple npm packages

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#315]
Let's use [lerna](https://github.com/lerna/lerna) to make this a monorepo with different packages:

* examples: This directory contains one or two examples, similar to the ones right now. They will help in manually testing the current state of the monorepo. Will not be published
* ui: Material-ui based ui components that represent a default user interface if people don't want to implement one themselves. Basicalle the contents of [Components/Controls](https://github.com/ory-am/editor/tree/prepare-next/src/editor/components/Controls). Will be published as, e.g. `ory-editor-default-ui`
* core: The core components without any plugins and uis
* plugins: A directory with multiple repos
  * slate
  * spacer
  * image
  * ...

ping @inyono wdyt?

**Comment by arekkas** [comment]
One big benefit of this will be that every tag will result in a new release for each of the packages. That means that all packages will always be on the same tag version. Similar to react and react-dom where both have versions `15.4.1`. It will save us angular-fuckups where each repository had their own versioning history and now they need to skip one major version (next release is Angular 4 instead of Angular 3)

**Comment by inyono** [comment]
Yep, sounds good. This was also my plan for the plugins, but it makes even more sense to do this in this repository.

**Comment by arekkas** [comment]
use lerna beta2
