### ISSUE TITLE
vendor: decide if we really need ramda

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#316]
ramda is used only in a few places, for example in webpack.config.js, which could probably be done in a one-liner

```js
const R = require('ramda')
R.reject(R.isNil)
```

**Comment by inyono** [comment]
Sure, kick it :) I like Ramda because the API is much more consistent than the JavaScript built-in methods. But it's not needed here.

**Comment by arekkas** [comment]
It's actually used in a couple of other places as well, let's keep it for now
