### ISSUE TITLE
core: replace webpack template with create-react-app

### ISSUE THREAD

**Issue by inyono** [ory-am/editor#78]
To continue our discussion from Monday (I think): If we decide to switch to `create-react-app`, we would lose some syntax stuff (class properties, probably more). Furthermore, css modules aren't supported yet. They work with a little hack, but might break after some updates. On the other hand, we would get a stable config... ;)

**Comment by inyono** [comment]
Can be closed, we now use ejected CRA-configs for the examples.

**Comment by arekkas** [comment]
:+1:
